server:
  port: 8089

spring:
  springdoc:
    api-docs:
      enabled: true
      path: '/v3/api-docs'
    swagger-ui:
      path: '/swagger-ui.html'
      doc-expansion: none
      disable-swagger-default-url: true

string_length:
  min: 1
  max: 2147483647